# Generated by Django 4.1.3 on 2023-10-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_dailyexerciseprogram_cool_down_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyexerciseprogram',
            old_name='weakly_program',
            new_name='weekly_program',
        ),
        migrations.AddConstraint(
            model_name='dailyexerciseprogram',
            constraint=models.UniqueConstraint(fields=('weekly_program', 'day'), name='unique_day_per_daily_program'),
        ),
        migrations.AddConstraint(
            model_name='weeklyexerciseprogram',
            constraint=models.UniqueConstraint(fields=('exercise_program', 'week'), name='unique_week_per_exercise_program'),
        ),
    ]
