# Generated by Django 4.1.3 on 2023-10-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_remove_dailyexerciseprogram_cool_down_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='توصیه')),
                ('exercise_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to='exercise.exerciseprogram', verbose_name='برنامه ورزشی')),
            ],
            options={
                'verbose_name': 'Exercise recommend',
                'verbose_name_plural': 'Exercise recommends',
                'ordering': ('-id',),
            },
        ),
    ]
