# Generated by Django 4.1.3 on 2023-09-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.PositiveIntegerField(default=0, verbose_name='height')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='height')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='weightt')),
            ],
        ),
    ]
