# Generated by Django 4.1.3 on 2023-09-21 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/%Y/%m/%d/users')),
                ('national_code', models.PositiveIntegerField(default=0, verbose_name='height')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='height')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='weight')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
