# Generated by Django 4.1.3 on 2023-09-23 12:03

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='kwargs',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationuser',
            name='type',
            field=models.CharField(default='NONE', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationuser',
            name='send_notify',
            field=models.BooleanField(default=True),
        ),
    ]
