# Generated by Django 4.2 on 2023-10-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_package_options_alter_package_price_and_more'),
        ('account', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='packages',
            field=models.ManyToManyField(related_name='users', to='package.package', verbose_name='پکیج ها'),
        ),
    ]
