# Generated by Django 4.2 on 2023-10-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='arm_size',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='سانتی متر', null=True, verbose_name='سایز بازو'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(default=0, help_text='سانتی متر', verbose_name='قد'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hip_size',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='سانتی متر', null=True, verbose_name='سایز ران'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='waist_size',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='سانتی متر', null=True, verbose_name='سایز کمر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='کیلوگرم', verbose_name='وزن'),
        ),
    ]
