# Generated by Django 4.2 on 2023-10-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_exerciseday_options_userprofile_chest_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseday',
            name='name',
            field=models.CharField(max_length=16, verbose_name='روز هفته'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='breakfast_time',
            field=models.CharField(default='-', max_length=8, verbose_name='زمان ترجیحی صبحانه'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dinner_time',
            field=models.CharField(default='-', max_length=8, verbose_name='زمان ترجیحی شام'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='launch_time',
            field=models.CharField(default='-', max_length=8, verbose_name='زمان ترجیجی ناهار'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='snack_time',
            field=models.CharField(default='-', max_length=8, verbose_name='زمان ترجیحی میان وعده'),
        ),
    ]
