# Generated by Django 4.2 on 2023-10-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_userprofile_national_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='modified_time',
            new_name='modified_at',
        ),
    ]
