# Generated by Django 4.2 on 2023-10-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_rename_create_time_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Special medicine name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chest_size',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='سانتی متر', null=True, verbose_name='سایز قفسه سینه'),
        ),
    ]
