# Generated by Django 4.2 on 2023-10-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_userprofile_medicine_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Profile token'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='نام داروی خاص'),
        ),
    ]
