# Generated by Django 4.1.3 on 2023-09-20 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'Sat'), ('1', 'Sun'), ('2', 'Mon'), ('3', 'Tue'), ('4', 'Wed'), ('5', 'Thu'), ('6', 'fri')], max_length=10, verbose_name='Day')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('rep', models.PositiveIntegerField(default=0, verbose_name='Repeat')),
                ('sets', models.PositiveIntegerField(default=0, verbose_name='Set')),
                ('info', models.TextField(verbose_name='Information')),
                ('day', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='program.days')),
            ],
        ),
        migrations.CreateModel(
            name='Diet_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100, verbose_name='food')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('energy', models.PositiveIntegerField(default=0, verbose_name='Energy')),
                ('info', models.TextField(verbose_name='Information')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.days')),
            ],
        ),
    ]
