# Generated by Django 4.1.3 on 2023-09-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet_program_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100, verbose_name='food')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('energy', models.PositiveIntegerField(default=0, verbose_name='Energy')),
                ('info', models.TextField(verbose_name='Information')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_program_objects', to='program.days')),
            ],
        ),
        migrations.CreateModel(
            name='Training_program_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('rep', models.PositiveIntegerField(default=0, verbose_name='Repeat')),
                ('sets', models.PositiveIntegerField(default=0, verbose_name='Set')),
                ('info', models.TextField(verbose_name='Information')),
                ('day', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='training_program_objects', to='program.days')),
            ],
        ),
        migrations.RemoveField(
            model_name='training_program',
            name='day',
        ),
        migrations.DeleteModel(
            name='Diet_program',
        ),
        migrations.DeleteModel(
            name='Training_program',
        ),
    ]
