# Generated by Django 4.1.3 on 2023-09-20 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0002_diet_program_object_training_program_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL),
        ),
    ]
