# Generated by Django 4.1.3 on 2023-09-20 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0003_alter_days_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='user',
            field=models.ForeignKey(default='sat', on_delete=django.db.models.deletion.CASCADE, related_name='days', to=settings.AUTH_USER_MODEL),
        ),
    ]
