# Generated by Django 4.1.3 on 2023-09-20 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0005_alter_days_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days',
            name='user',
        ),
        migrations.AddField(
            model_name='diet_program_object',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_diet_program', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training_program_object',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_training_program', to=settings.AUTH_USER_MODEL),
        ),
    ]
