# Generated by Django 4.1.3 on 2023-09-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_remove_days_user_diet_program_object_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
        migrations.RemoveField(
            model_name='training_program_object',
            name='name',
        ),
        migrations.AddField(
            model_name='training_program_object',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_training_programs', to='program.sport'),
        ),
        migrations.AlterField(
            model_name='diet_program_object',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_diet_programs', to='program.food'),
        ),
    ]
