# Generated by Django 4.1.3 on 2023-09-20 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_food_sport_rename_days_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet_program_object',
            name='created_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet_program_object',
            name='moified_time',
            field=models.DateField(auto_now=True, verbose_name='Modified_time'),
        ),
        migrations.AddField(
            model_name='training_program_object',
            name='created_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training_program_object',
            name='moified_time',
            field=models.DateField(auto_now=True, verbose_name='Modified_time'),
        ),
    ]
