# Generated by Django 4.1.3 on 2023-09-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_alter_day_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet_program_object',
            name='quantity',
        ),
        migrations.AddField(
            model_name='diet_program_object',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='amount'),
        ),
    ]
