# Generated by Django 4.1.3 on 2023-09-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_remove_diet_program_object_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diet_program_object',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='training_program_object',
            options={'ordering': ('-id',)},
        ),
    ]
