# Generated by Django 4.1.3 on 2023-09-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_alter_diet_program_object_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet_program_object',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created_time'),
        ),
        migrations.AlterField(
            model_name='diet_program_object',
            name='moified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified_time'),
        ),
        migrations.AlterField(
            model_name='training_program_object',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created_time'),
        ),
        migrations.AlterField(
            model_name='training_program_object',
            name='moified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified_time'),
        ),
    ]
