# Generated by Django 4.1.3 on 2023-09-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_alter_diet_program_object_created_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ('-id',)},
        ),
    ]
