# Generated by Django 4.1.3 on 2023-09-25 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_alter_food_options_alter_sport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet_program_object_free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], max_length=15)),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='amount')),
                ('energy', models.PositiveIntegerField(default=0, verbose_name='Energy')),
                ('description', models.TextField(null=True, verbose_name='Information')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created_time')),
                ('moified_time', models.DateTimeField(auto_now=True, verbose_name='Modified_time')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_diet_programs_free', to='program.food')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
