# Generated by Django 4.2 on 2023-12-25 16:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='اختیاری', max_length=64, null=True, verbose_name='عنوان مدرک')),
                ('picture', models.ImageField(upload_to='images/certificates', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدارک',
            },
        ),
        migrations.CreateModel(
            name='FreeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=64, verbose_name='Content title')),
                ('short_description', models.CharField(help_text='Date, extra info, ...', max_length=64, verbose_name='Short description')),
                ('text', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
            ],
            options={
                'verbose_name': 'Free content',
                'verbose_name_plural': 'Free contents',
                'ordering': ('-id',),
            },
        ),
    ]
