# Generated by Django 4.2 on 2023-12-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diet', '0001_initial'),
        ('exercise', '0006_alter_exerciserecommend_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='اختیاری', max_length=64, null=True, verbose_name='عنوان مدرک')),
                ('picture', models.ImageField(upload_to='images/certificates', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'مدرک',
                'verbose_name_plural': 'مدارک',
            },
        ),
        migrations.CreateModel(
            name='FreeDailyDietProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], default='0', max_length=8, verbose_name='روز')),
            ],
            options={
                'verbose_name': 'برنامه روزانه',
                'verbose_name_plural': 'برنامه های روزانه',
                'ordering': ('day',),
            },
        ),
        migrations.CreateModel(
            name='FreeDailyExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], default='0', max_length=16, verbose_name='روز هفته')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'برنامه روزانه',
                'verbose_name_plural': 'برنامه های روزانه',
                'ordering': ('day',),
            },
        ),
        migrations.CreateModel(
            name='FreeDietMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_diet_meals', to='public.freedailydietprogram', verbose_name='برنامه روزانه')),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_diet_meals', to='diet.meal', verbose_name='وعده')),
            ],
            options={
                'verbose_name': 'وعده روزانه',
                'verbose_name_plural': 'وعده های روزانه',
                'ordering': ('meal__time',),
            },
        ),
        migrations.CreateModel(
            name='FreeDietProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
            ],
            options={
                'verbose_name': 'برنامه غذایی رایگان',
                'verbose_name_plural': 'برنامه های غذایی رایگان',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='FreeExerciseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
            ],
            options={
                'verbose_name': 'برنامه ورزشی رایگان',
                'verbose_name_plural': 'برنامه\u200cهای ورزشی رایگان',
            },
        ),
        migrations.CreateModel(
            name='FreeWeeklyExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('0', 'هفته اول'), ('1', 'هفته دوم'), ('2', 'هفته سوم'), ('3', 'هفته چهارم')], max_length=32, verbose_name='هفته')),
                ('warm_up', models.CharField(blank=True, help_text='مثال: 5 - 10', max_length=16, null=True, verbose_name='زمان گرم کردن (دقیقه)')),
                ('cool_down', models.CharField(blank=True, help_text='مثال: 5 - 10', max_length=16, null=True, verbose_name='زمان سرد کردن (دقیقه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('exercise_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_weekly_exercises', to='public.freeexerciseprogram', verbose_name='برنامه ورزشی')),
            ],
            options={
                'verbose_name': 'برنامه هفتگی',
                'verbose_name_plural': 'برنامه هفتگی',
                'ordering': ('week',),
            },
        ),
        migrations.CreateModel(
            name='FreeMealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='مقدار')),
                ('amount_unit', models.CharField(blank=True, help_text='مثال: گرم، میلی گرم، لیوان و...', max_length=128, null=True, verbose_name='واحد مقدار')),
                ('energy', models.PositiveBigIntegerField(default=0, verbose_name='انرژی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modify time')),
                ('diet_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_meal_foods', to='public.freedietmeal', verbose_name='وعده روزانه')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='free_meal_foods', to='diet.food', verbose_name='غذا')),
            ],
            options={
                'verbose_name': 'غذای وعده',
                'verbose_name_plural': 'غذاهای وعده',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='FreeExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveBigIntegerField(default=1, verbose_name='ست')),
                ('number', models.PositiveBigIntegerField(default=1, verbose_name='تعداد در هر ست')),
                ('rest', models.PositiveBigIntegerField(default=20, verbose_name='زمان استراحت (ثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('daily_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_exercises', to='public.freedailyexercise', verbose_name='برنامه روزانه')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='free_exercises', to='exercise.workout', verbose_name='ورزش')),
            ],
            options={
                'verbose_name': 'ورزش',
                'verbose_name_plural': 'ورزش',
            },
        ),
        migrations.AddField(
            model_name='freedailyexercise',
            name='weekly_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_daily_exercises', to='public.freeweeklyexercise', verbose_name='برنامه هفتگی'),
        ),
        migrations.AddField(
            model_name='freedailydietprogram',
            name='diet_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_daily_diet_programs', to='public.freedietprogram', verbose_name='برنامه غذایی'),
        ),
        migrations.AddConstraint(
            model_name='freeweeklyexercise',
            constraint=models.UniqueConstraint(fields=('exercise_program', 'week'), name='unique_week_per_free_exercise_program'),
        ),
        migrations.AddConstraint(
            model_name='freedailyexercise',
            constraint=models.UniqueConstraint(fields=('weekly_program', 'day'), name='unique_day_per_free_weekly_exercise'),
        ),
        migrations.AddConstraint(
            model_name='freedailydietprogram',
            constraint=models.UniqueConstraint(fields=('diet_program', 'day'), name='unique_day_per_free_program'),
        ),
    ]
