# Generated by Django 4.1.3 on 2023-09-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='picture',
            field=models.ImageField(upload_to='images/certificates'),
        ),
    ]
