# Generated by Django 4.2 on 2023-11-30 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_freedailyexercise_freeexerciseprogram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeexerciseprogram',
            options={'verbose_name': 'برنامه ورزشی رایگان', 'verbose_name_plural': 'برنامه\u200cهای ورزشی رایگان'},
        ),
    ]
