# Generated by Django 4.2 on 2023-10-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('diet', 'رژیم غذایی'), ('workout', 'ورزش'), ('crossfit', 'Crossfit'), ('workout_diet', 'Workout + Diet'), ('crossfit_diet', 'Crossfit + Diet'), ('any_diet', 'Any sport + Diet'), ('offline', 'Offline')], default='diet', max_length=128, verbose_name='Package type'),
        ),
    ]
