# Generated by Django 4.2 on 2023-10-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_alter_package_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('id',), 'verbose_name': 'پکیج', 'verbose_name_plural': 'پکیج ها'},
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.IntegerField(default=0, help_text='ریال', verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('diet', 'رژیم غذایی'), ('workout', 'بدنسازی'), ('crossfit', 'کراسفیت'), ('workout_diet', 'بدنسازی + رژیم غذایی'), ('crossfit_diet', 'کراسفیت + رژیم غذایی'), ('any_diet', 'هر نوع ورزش + رژیم غذایی'), ('offline', 'آفلاین')], default='diet', max_length=128, verbose_name='نوع پکیج'),
        ),
    ]
