# Generated by Django 4.2 on 2023-10-24 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/%Y/%m/%d/users', verbose_name='User picture')),
                ('national_code', models.PositiveIntegerField(default=0, verbose_name='National code')),
                ('last_exercise', models.TextField(verbose_name='Last time exercise')),
                ('goal_of_program', models.TextField(verbose_name='Goal of getting program')),
                ('exercise_systems', models.TextField(verbose_name='Exercise system experience')),
                ('additional_explain', models.TextField(verbose_name='Additional explanations')),
                ('weight', models.PositiveIntegerField(default=0, verbose_name='Weight')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Height')),
                ('waist_size', models.PositiveIntegerField(default=0, null=True, verbose_name='Waist size')),
                ('hip_size', models.PositiveIntegerField(default=0, null=True, verbose_name='Hip size')),
                ('arm_size', models.PositiveIntegerField(default=0, null=True, verbose_name='Arm size')),
                ('family_disease', models.BooleanField(default=False, verbose_name='Family disease history')),
                ('special_disease', models.BooleanField(default=False, verbose_name='Special disease')),
                ('special_medicine', models.BooleanField(default=False, verbose_name='Special medicine')),
                ('breakfast_time', models.CharField(default='07:00', max_length=8, verbose_name='Breakfast time willing')),
                ('snack_time', models.CharField(default='10:00', max_length=8, verbose_name='Snack time willing')),
                ('launch_time', models.CharField(default='12:30', max_length=8, verbose_name='Launch time willing')),
                ('dinner_time', models.CharField(default='18:00', max_length=8, verbose_name='Dinner time willing')),
                ('use_supplement', models.BooleanField(default=False, verbose_name='Use supplement')),
                ('want_supplement', models.BooleanField(default=False, verbose_name='Want supplement')),
                ('used_steroids', models.BooleanField(default=False, verbose_name='Used steroids')),
                ('in_diet', models.BooleanField(default=False, verbose_name='Had/Has diet')),
                ('vegetarian', models.BooleanField(default=False, verbose_name='Vegetarian')),
                ('physical_damage', models.BooleanField(default=False, verbose_name='Physical damage')),
                ('regular_exercise', models.BooleanField(default=False, verbose_name='Regular/Pro exercise')),
                ('doing_exercise', models.CharField(default='I do not exercise', max_length=64, verbose_name='Doing exercise')),
                ('body_composition', models.ImageField(null=True, upload_to='images/%Y/%m/%d/users/docs', verbose_name='Body composition')),
                ('body_checkup', models.ImageField(null=True, upload_to='images/%Y/%m/%d/users/docs', verbose_name='Body checkup')),
                ('body_picture', models.ImageField(null=True, upload_to='images/%Y/%m/%d/users/docs', verbose_name='Body picture')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
                'ordering': ('-id',),
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
