# Generated by Django 4.2 on 2023-11-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_userprofile_token_alter_userprofile_medicine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='body_checkup',
            field=models.FileField(blank=True, null=True, upload_to='images/users/docs', verbose_name='آزمایش چکاپ بدن'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='body_composition',
            field=models.FileField(blank=True, null=True, upload_to='images/users/docs', verbose_name='آزمایش ترکیب بدنی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='body_picture',
            field=models.FileField(blank=True, null=True, upload_to='images/users/docs', verbose_name='تصویر بدن'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='توکن پروفایل'),
        ),
    ]
