# Generated by Django 4.2 on 2023-10-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_exerciserecommend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciserecommend',
            options={'ordering': ('id',), 'verbose_name': 'توصیه ورزشی', 'verbose_name_plural': 'توصیه های ورزشی'},
        ),
    ]
