# Generated by Django 4.2 on 2023-12-26 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.ManyToManyField(related_name='purchase_requests', to='package.package', verbose_name='packages')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_request', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'Purchase request',
                'verbose_name_plural': 'Purchase requests',
            },
        ),
    ]
