# Generated by Django 4.2 on 2023-12-25 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='آدرس ایمیل')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True, verbose_name='شماره تماس')),
                ('role', models.CharField(choices=[('normal_user', 'کاربر عادی'), ('super_user', 'کاربر ادمین')], default='normal_user', max_length=20, verbose_name='نقش کاربر')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('packages', models.ManyToManyField(blank=True, related_name='users', to='package.package', verbose_name='پکیج ها')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ExerciseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='روز هفته')),
            ],
            options={
                'verbose_name': 'روز تمرین',
                'verbose_name_plural': 'روزهای تمرین',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='توکن پروفایل')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/users', verbose_name='تصویر کاربر')),
                ('national_code', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='کد ملی')),
                ('weight', models.PositiveIntegerField(default=0, help_text='کیلوگرم', verbose_name='وزن')),
                ('height', models.PositiveIntegerField(default=0, help_text='سانتی متر', verbose_name='قد')),
                ('waist_size', models.PositiveIntegerField(blank=True, default=0, help_text='سانتی متر', null=True, verbose_name='سایز کمر')),
                ('hip_size', models.PositiveIntegerField(blank=True, default=0, help_text='سانتی متر', null=True, verbose_name='سایز ران')),
                ('arm_size', models.PositiveIntegerField(blank=True, default=0, help_text='سانتی متر', null=True, verbose_name='سایز بازو')),
                ('chest_size', models.PositiveIntegerField(blank=True, default=0, help_text='سانتی متر', null=True, verbose_name='سایز قفسه سینه')),
                ('physical_damage', models.BooleanField(default=False, verbose_name='سابقه آسیب فیزیکی')),
                ('regular_exercise', models.BooleanField(default=False, verbose_name='سابقه تمرین منظم/حرفه ای')),
                ('exercise_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان تمرین')),
                ('doing_exercise', models.CharField(default='تمرین ورزشی ندارم', max_length=64, verbose_name='انجام تمرین ورزشی')),
                ('last_exercise', models.TextField(blank=True, null=True, verbose_name='آخرین زمان ورزش')),
                ('goal_of_program', models.TextField(blank=True, null=True, verbose_name='هدف دریافت برنامه')),
                ('exercise_systems', models.TextField(blank=True, null=True, verbose_name='سیستم های تمرینی تجربه شده')),
                ('additional_explain', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('family_disease', models.BooleanField(default=False, verbose_name='سابقه بیماری خانوادگی')),
                ('family_disease_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان بیماری خانوادگی')),
                ('special_disease', models.BooleanField(default=False, verbose_name='دارای بیماری خاص')),
                ('special_disease_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان بیماری خاص')),
                ('special_medicine', models.BooleanField(default=False, verbose_name='استفاده از داروی خاص')),
                ('medicine_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام داروی خاص')),
                ('breakfast_time', models.CharField(default='-', max_length=8, verbose_name='زمان ترجیحی صبحانه')),
                ('snack_time', models.CharField(default='-', max_length=8, verbose_name='زمان ترجیحی میان وعده')),
                ('launch_time', models.CharField(default='-', max_length=8, verbose_name='زمان ترجیجی ناهار')),
                ('dinner_time', models.CharField(default='-', max_length=8, verbose_name='زمان ترجیحی شام')),
                ('use_supplement', models.BooleanField(default=False, verbose_name='درحال مصرف مکمل ورزشی/غذایی')),
                ('supplement_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان مکمل')),
                ('want_supplement', models.BooleanField(default=False, verbose_name='خواستار مکمل ورزشی/غذایی')),
                ('used_steroids', models.BooleanField(default=False, verbose_name='سابقه استفاده از داروی استروییدی')),
                ('steroids_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام داروی استروئیدی')),
                ('in_diet', models.BooleanField(default=False, verbose_name='رژیم غذایی داشته/دارد')),
                ('diet_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان رژیم')),
                ('vegetarian', models.BooleanField(default=False, verbose_name='گیاه خوار')),
                ('body_composition', models.FileField(blank=True, null=True, upload_to='images/users/docs', verbose_name='آزمایش ترکیب بدنی')),
                ('body_checkup', models.FileField(blank=True, null=True, upload_to='images/users/docs', verbose_name='آزمایش چکاپ بدن')),
                ('body_picture', models.FileField(blank=True, null=True, upload_to='images/users/docs', verbose_name='تصویر بدن')),
                ('verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('exercise_days', models.ManyToManyField(blank=True, related_name='user_profile', to='account.exerciseday', verbose_name='روزهای ترجیحی تمرین ورزشی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل کاربران',
                'ordering': ('-id',),
            },
        ),
    ]
