# Generated by Django 4.2 on 2023-12-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='snack_time',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='am_snack_time',
            field=models.CharField(default='-', max_length=8, verbose_name='AM Snack time willing'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pm_snack_time',
            field=models.CharField(default='-', max_length=8, verbose_name='PM Snack time willing'),
        ),
    ]
