# Generated by Django 4.2 on 2023-12-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_am_snack_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='damage_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Damage type/area'),
        ),
    ]
