# Generated by Django 4.2 on 2023-10-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_exerciseday_alter_userprofile_body_checkup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciseday',
            options={'ordering': ('id',), 'verbose_name': 'روز تمرین', 'verbose_name_plural': 'روزهای تمرین'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='chest_size',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='سانتی متر', null=True, verbose_name='Chest size'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exercise_days',
            field=models.ManyToManyField(blank=True, related_name='user_profile', to='account.exerciseday', verbose_name='روزهای ترجیحی تمرین ورزشی'),
        ),
    ]
