# Generated by Django 4.2 on 2023-10-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_exerciseday_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='national_code',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='کد ملی'),
        ),
    ]
