# Generated by Django 4.2 on 2023-12-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_userprofile_exercise_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diet_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Diet name'),
        ),
    ]
