# Generated by Django 4.2 on 2023-12-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_userprofile_diet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='diet_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان رژیم'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان تمرین'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='family_disease_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان بیماری خانوادگی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='special_disease_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان بیماری خاص'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='steroids_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='نام داروی استروئیدی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='supplement_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='عنوان مکمل'),
        ),
    ]
