# Generated by Django 4.2 on 2023-10-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_freedailydietprogram_freedietmeal_freedietprogram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freedailydietprogram',
            options={'ordering': ('day',), 'verbose_name': 'برنامه روزانه', 'verbose_name_plural': 'برنامه های روزانه'},
        ),
        migrations.AlterModelOptions(
            name='freedietmeal',
            options={'ordering': ('meal__time',), 'verbose_name': 'وعده روزانه', 'verbose_name_plural': 'وعده های روزانه'},
        ),
        migrations.AlterModelOptions(
            name='freedietprogram',
            options={'verbose_name': 'برنامه غذایی رایگان', 'verbose_name_plural': 'برنامه های غذایی رایگان'},
        ),
        migrations.AlterField(
            model_name='freedailydietprogram',
            name='day',
            field=models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], default='0', max_length=8, verbose_name='روز'),
        ),
        migrations.AlterField(
            model_name='freedailydietprogram',
            name='diet_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_daily_diet_programs', to='public.freedietprogram', verbose_name='برنامه غذایی'),
        ),
        migrations.AlterField(
            model_name='freedietprogram',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='freemealfood',
            name='diet_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_meal_foods', to='public.freedietmeal', verbose_name='وعده روزانه'),
        ),
        migrations.AddConstraint(
            model_name='freedailydietprogram',
            constraint=models.UniqueConstraint(fields=('diet_program', 'day'), name='unique_day_per_free_program'),
        ),
    ]
