# Generated by Django 4.1.3 on 2023-10-20 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modify time')),
            ],
            options={
                'verbose_name': 'Daily meal',
                'verbose_name_plural': 'Daily meals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DailyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'Saturday'), ('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday')], default='0', max_length=32, verbose_name='Day of weak')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modify time')),
            ],
            options={
                'verbose_name': 'Daily program',
                'verbose_name_plural': 'Daily programs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DietRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='Recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
            ],
            options={
                'verbose_name': 'Recommend',
                'verbose_name_plural': 'Recommends',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Meal title')),
                ('time', models.TimeField(blank=True, max_length=64, null=True, verbose_name='Meal time')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='Amount')),
                ('amout_unit', models.CharField(blank=True, help_text='example: (gram, milligram, glass, ...)', max_length=128, null=True, verbose_name='Amount unit')),
                ('energy', models.PositiveBigIntegerField(default=0, verbose_name='Energy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modify time')),
                ('daily_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_foods', to='program.dailymeal', verbose_name='Daily meal')),
            ],
            options={
                'verbose_name': "Meal's food",
                'verbose_name_plural': "Meal's foods",
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WeaklyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='example: Program of first month', max_length=128, verbose_name='Program title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modify time')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='DietMeal',
        ),
        migrations.AlterModelOptions(
            name='dietprogram',
            options={'ordering': ('-id',), 'verbose_name': 'Diet program', 'verbose_name_plural': 'Diet programs'},
        ),
        migrations.RemoveField(
            model_name='dietprogram',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='dietprogram',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dietprogram',
            name='day',
        ),
        migrations.RemoveField(
            model_name='dietprogram',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dietprogram',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='dietprogram',
            name='food',
        ),
        migrations.AddField(
            model_name='dietprogram',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='dietprogram',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diet_programs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='dietprogramfree',
            name='day',
            field=models.CharField(choices=[('0', 'Saturday'), ('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday')], default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='dietprogramfree',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diet_program_free', to='program.food'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Food title'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='day',
            field=models.CharField(choices=[('0', 'Saturday'), ('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday'), ('5', 'Thursday'), ('6', 'Friday')], default='0', max_length=15),
        ),
        migrations.AddField(
            model_name='weaklyprogram',
            name='diet_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='program.dietprogram', verbose_name='Diet program'),
        ),
        migrations.AddField(
            model_name='mealfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_foods', to='program.food', verbose_name='Food'),
        ),
        migrations.AddField(
            model_name='dietrecommend',
            name='diet_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to='program.dietprogram', verbose_name='Diet Program'),
        ),
        migrations.AddField(
            model_name='dailyprogram',
            name='weakly_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_programs', to='program.weaklyprogram', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='daily_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meals', to='program.dailyprogram', verbose_name='Daily program'),
        ),
        migrations.AddField(
            model_name='dailymeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_meals', to='program.meal', verbose_name='Meal'),
        ),
    ]
