# Generated by Django 4.1.3 on 2023-10-21 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietprogramcategory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dietprogramfree',
            name='food',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='category',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainingprogramcategory',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='dailydietmeal',
            options={'ordering': ('created_at',), 'verbose_name': 'وعده روزانه', 'verbose_name_plural': 'وعده های روزانه'},
        ),
        migrations.AlterModelOptions(
            name='dailydietprogram',
            options={'ordering': ('day',), 'verbose_name': 'برنامه روزانه', 'verbose_name_plural': 'برنامه های روزانه کابر'},
        ),
        migrations.AlterModelOptions(
            name='dietprogram',
            options={'ordering': ('-id',), 'verbose_name': 'برنامه غذایی کاربر', 'verbose_name_plural': 'برنامه های غذایی کاربران'},
        ),
        migrations.AlterModelOptions(
            name='dietrecommend',
            options={'ordering': ('id',), 'verbose_name': 'توصیه', 'verbose_name_plural': 'توصیه ها'},
        ),
        migrations.AlterModelOptions(
            name='mealfood',
            options={'ordering': ('created_at',), 'verbose_name': 'غذای وعده', 'verbose_name_plural': 'غذاهای وعده'},
        ),
        migrations.AlterField(
            model_name='dailydietprogram',
            name='diet_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_programs', to='program.dietprogram', verbose_name='برنامه کاربر'),
        ),
        migrations.AlterField(
            model_name='dietprogram',
            name='title',
            field=models.CharField(help_text='مثال: برنامه ماه اول', max_length=64, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.PositiveIntegerField(default=0, verbose_name='کالری'),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=128, verbose_name='عنوان غذا'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(blank=True, max_length=64, null=True, verbose_name='زمان وعده'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='title',
            field=models.CharField(max_length=128, verbose_name='عنوان وعده'),
        ),
        migrations.AddConstraint(
            model_name='dailydietprogram',
            constraint=models.UniqueConstraint(fields=('diet_program', 'day'), name='unique_day_per_program'),
        ),
        migrations.DeleteModel(
            name='DietProgramCategory',
        ),
        migrations.DeleteModel(
            name='DietProgramFree',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='TrainingProgram',
        ),
        migrations.DeleteModel(
            name='TrainingProgramCategory',
        ),
    ]
