# Generated by Django 4.1.3 on 2023-10-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_dailymeal_dailyprogram_dietrecommend_meal_mealfood_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietprogram',
            options={'ordering': ('-id',), 'verbose_name': 'برنامه غذایی', 'verbose_name_plural': 'برنامه های غذایی'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('-id',), 'verbose_name': 'غذا', 'verbose_name_plural': 'غذاها'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ('-id',), 'verbose_name': 'وعده', 'verbose_name_plural': 'وعده ها'},
        ),
        migrations.AlterModelOptions(
            name='weaklyprogram',
            options={'ordering': ('-created_at',), 'verbose_name': 'برنامه', 'verbose_name_plural': 'برنامه ها'},
        ),
        migrations.AlterField(
            model_name='dailymeal',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_meals', to='program.meal', verbose_name='وعده'),
        ),
        migrations.AlterField(
            model_name='dailyprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='dailyprogram',
            name='day',
            field=models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], default='0', max_length=32, verbose_name='Day of weak'),
        ),
        migrations.AlterField(
            model_name='dailyprogram',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='dailyprogram',
            name='weakly_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_programs', to='program.weaklyprogram', verbose_name='برنامه'),
        ),
        migrations.AlterField(
            model_name='dietprogram',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='dietprogramfree',
            name='day',
            field=models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='dietrecommend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_foods', to='program.food', verbose_name='غذا'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='day',
            field=models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], default='0', max_length=15),
        ),
        migrations.AlterField(
            model_name='weaklyprogram',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='weaklyprogram',
            name='diet_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='program.dietprogram', verbose_name='برنامه غذایی'),
        ),
        migrations.AlterField(
            model_name='weaklyprogram',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش'),
        ),
        migrations.AlterField(
            model_name='weaklyprogram',
            name='title',
            field=models.CharField(help_text='مثال: برنامه ماه اول', max_length=128, verbose_name='عنوان برنامه'),
        ),
    ]
