# Generated by Django 4.2 on 2023-10-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_remove_dietprogramcategory_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.PositiveIntegerField(default=0, help_text='Calories in a unit', verbose_name='کالری'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(blank=True, help_text='example: 15:30', max_length=64, null=True, verbose_name='زمان وعده'),
        ),
    ]
