# Generated by Django 4.1.3 on 2023-10-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_alter_dietprogram_options_alter_food_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymeal',
            options={'ordering': ('-created_at',), 'verbose_name': 'وعده روزانه', 'verbose_name_plural': 'وعده های روزانه'},
        ),
        migrations.AlterModelOptions(
            name='dailyprogram',
            options={'ordering': ('-created_at',), 'verbose_name': 'برنامه روزانه', 'verbose_name_plural': 'برنامه های روزانه'},
        ),
        migrations.AlterModelOptions(
            name='dietrecommend',
            options={'ordering': ('-created_at',), 'verbose_name': 'توصیه', 'verbose_name_plural': 'توصیه ها'},
        ),
        migrations.AlterModelOptions(
            name='mealfood',
            options={'ordering': ('-created_at',), 'verbose_name': 'غذای وعده', 'verbose_name_plural': 'غذاهای وعده'},
        ),
        migrations.AlterField(
            model_name='dailymeal',
            name='daily_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meals', to='program.dailyprogram', verbose_name='برنامه روزانه'),
        ),
        migrations.AlterField(
            model_name='dailyprogram',
            name='day',
            field=models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], default='0', max_length=32, verbose_name='روز هفته'),
        ),
        migrations.AlterField(
            model_name='dietrecommend',
            name='diet_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to='program.dietprogram', verbose_name='برنامه غذایی'),
        ),
        migrations.AlterField(
            model_name='dietrecommend',
            name='text',
            field=models.CharField(max_length=128, verbose_name='توصیه'),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='amout_unit',
            field=models.CharField(blank=True, help_text='مثال: گرم، میلی گرم، لیوان و...', max_length=128, null=True, verbose_name='واحد مقدار'),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='daily_meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_foods', to='program.dailymeal', verbose_name='وعده روزانه'),
        ),
        migrations.AlterField(
            model_name='mealfood',
            name='energy',
            field=models.PositiveBigIntegerField(default=0, verbose_name='انرژی'),
        ),
    ]
