# Generated by Django 4.2 on 2023-11-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_package_options_alter_package_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='fw_class',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='FontAwesome css class'),
        ),
        migrations.AddField(
            model_name='package',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/packages/icons', verbose_name='Package icon'),
        ),
    ]
