# Generated by Django 4.2 on 2023-11-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_package_fw_class_package_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='buy_link',
            field=models.URLField(blank=True, null=True, verbose_name='Purchase link'),
        ),
        migrations.AlterField(
            model_name='package',
            name='fw_class',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='CSS class (FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/packages/icons', verbose_name='آیکون پکیج'),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('diet', 'رژیم غذایی'), ('workout', 'بدنسازی'), ('crossfit', 'کراسفیت'), ('workout_diet', 'بدنسازی + رژیم غذایی'), ('crossfit_diet', 'کراسفیت + رژیم غذایی'), ('any_diet', 'هر ورزش تخصصی + غذایی'), ('offline', 'آفلاین')], default='diet', max_length=128, verbose_name='نوع پکیج'),
        ),
    ]
