# Generated by Django 4.2 on 2023-12-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_package_buy_link_alter_package_fw_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='buy_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک خرید'),
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('diet', 'رژیم غذایی'), ('workout', 'بدنسازی'), ('crossfit', 'کراسفیت'), ('workout_diet', 'بدنسازی + رژیم غذایی'), ('crossfit_diet', 'کراسفیت + رژیم غذایی'), ('private_workout_diet', 'بدنسازی خصوصی + غذایی'), ('any_diet', 'هر ورزش تخصصی + غذایی'), ('offline', 'آفلاین')], default='diet', max_length=128, verbose_name='نوع پکیج'),
        ),
    ]
