# Generated by Django 4.2 on 2023-12-25 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_alter_package_buy_link_alter_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('diet', 'رژیم غذایی'), ('workout', 'بدنسازی'), ('crossfit', 'کراسفیت'), ('workout_diet', 'بدنسازی + رژیم غذایی'), ('crossfit_diet', 'کراسفیت + رژیم غذایی'), ('private_workout_diet', 'بدنسازی خصوصی'), ('any_diet', 'هر ورزش تخصصی'), ('offline', 'آفلاین')], default='diet', max_length=128, verbose_name='نوع پکیج'),
        ),
        migrations.CreateModel(
            name='PackageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_info', to='package.package', verbose_name='پکیج')),
            ],
            options={
                'verbose_name': 'Package info',
                'verbose_name_plural': 'Package infos',
            },
        ),
    ]
