# Generated by Django 4.2 on 2023-12-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_alter_package_type_packageinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packageinfo',
            options={'verbose_name': 'توضیح پکیج', 'verbose_name_plural': 'توضیحات پکیج'},
        ),
        migrations.AlterField(
            model_name='packageinfo',
            name='text',
            field=models.CharField(max_length=255, verbose_name='متن'),
        ),
    ]
