# Generated by Django 4.2 on 2023-12-25 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExerciseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], default='0', max_length=16, verbose_name='روز هفته')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'برنامه روزانه',
                'verbose_name_plural': 'برنامه های روزانه',
                'ordering': ('day',),
            },
        ),
        migrations.CreateModel(
            name='ExerciseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثال: برنامه ورزشی ماه اول', max_length=64, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_programs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'برنامه ورزشی',
                'verbose_name_plural': 'برنامه های ورزشی کاربران',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان ورزش')),
                ('level', models.CharField(blank=True, choices=[('0', 'آسان'), ('1', 'عادی'), ('2', 'سخت')], max_length=32, null=True, verbose_name='سطح (اختیاری)')),
            ],
            options={
                'verbose_name': 'ورزش',
                'verbose_name_plural': 'ورزش ها',
            },
        ),
        migrations.CreateModel(
            name='WeeklyExerciseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('0', 'هفته اول'), ('1', 'هفته دوم'), ('2', 'هفته سوم'), ('3', 'هفته چهارم')], max_length=32, verbose_name='هفته')),
                ('warm_up', models.CharField(blank=True, help_text='مثال: 5 - 10', max_length=16, null=True, verbose_name='زمان گرم کردن (دقیقه)')),
                ('cool_down', models.CharField(blank=True, help_text='مثال: 5 - 10', max_length=16, null=True, verbose_name='زمان سرد کردن (دقیقه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('exercise_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_programs', to='exercise.exerciseprogram', verbose_name='برنامه ورزشی')),
            ],
            options={
                'verbose_name': 'برنامه هفتگی',
                'verbose_name_plural': 'برنامه هفتگی',
                'ordering': ('week',),
            },
        ),
        migrations.CreateModel(
            name='ExerciseRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128, verbose_name='توصیه')),
                ('exercise_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to='exercise.exerciseprogram', verbose_name='برنامه ورزشی')),
            ],
            options={
                'verbose_name': 'توصیه ورزشی',
                'verbose_name_plural': 'توصیه های ورزشی',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveBigIntegerField(default=1, verbose_name='ست')),
                ('number', models.PositiveBigIntegerField(default=1, verbose_name='تعداد در هر ست')),
                ('rest', models.PositiveBigIntegerField(default=20, verbose_name='زمان استراحت (ثانیه)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('daily_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise.dailyexerciseprogram', verbose_name='برنامه روزانه')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='exercise.workout', verbose_name='ورزش')),
            ],
            options={
                'verbose_name': 'ورزش',
                'verbose_name_plural': 'ورزش',
            },
        ),
        migrations.AddField(
            model_name='dailyexerciseprogram',
            name='weekly_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_programs', to='exercise.weeklyexerciseprogram', verbose_name='برنامه هفتگی'),
        ),
        migrations.AddConstraint(
            model_name='weeklyexerciseprogram',
            constraint=models.UniqueConstraint(fields=('exercise_program', 'week'), name='unique_week_per_exercise_program'),
        ),
        migrations.AddConstraint(
            model_name='dailyexerciseprogram',
            constraint=models.UniqueConstraint(fields=('weekly_program', 'day'), name='unique_day_per_daily_program'),
        ),
    ]
