# Generated by Django 4.2 on 2023-10-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_alter_certificate_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, help_text='Optional', max_length=64, null=True, verbose_name='Certificate title'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='picture',
            field=models.ImageField(upload_to='images/certificates', verbose_name='Picture'),
        ),
    ]
