# Generated by Django 4.2 on 2023-10-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_remove_dietprogramcategory_user_and_more'),
        ('public', '0003_alter_certificate_options_certificate_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeDailyDietProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'شنبه'), ('1', 'یکشنبه'), ('2', 'دوشنبه'), ('3', 'سه شنبه'), ('4', 'چهارشنبه'), ('5', 'پنجشنبه'), ('6', 'جمعه')], default='0', max_length=8, verbose_name='Day')),
            ],
            options={
                'verbose_name': 'Free daily program',
                'verbose_name_plural': 'Free daily programs',
                'ordering': ('day',),
            },
        ),
        migrations.CreateModel(
            name='FreeDietMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_diet_meals', to='public.freedailydietprogram', verbose_name='برنامه روزانه')),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_diet_meals', to='program.meal', verbose_name='وعده')),
            ],
            options={
                'verbose_name': 'Free diet meal',
                'verbose_name_plural': 'Free diet meals',
                'ordering': ('meal__time',),
            },
        ),
        migrations.CreateModel(
            name='FreeDietProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
            ],
            options={
                'verbose_name': 'Free diet program',
                'verbose_name_plural': 'Free diet programs',
            },
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'مدرک', 'verbose_name_plural': 'مدارک'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='picture',
            field=models.ImageField(upload_to='images/certificates', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(blank=True, help_text='اختیاری', max_length=64, null=True, verbose_name='عنوان مدرک'),
        ),
        migrations.CreateModel(
            name='FreeMealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='مقدار')),
                ('amount_unit', models.CharField(blank=True, help_text='مثال: گرم، میلی گرم، لیوان و...', max_length=128, null=True, verbose_name='واحد مقدار')),
                ('energy', models.PositiveBigIntegerField(default=0, verbose_name='انرژی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modify time')),
                ('diet_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_meal_foods', to='public.freedietmeal', verbose_name='Diet meal')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='free_meal_foods', to='program.food', verbose_name='غذا')),
            ],
            options={
                'verbose_name': 'غذای وعده',
                'verbose_name_plural': 'غذاهای وعده',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='freedailydietprogram',
            name='diet_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_daily_diet_programs', to='public.freedietprogram', verbose_name='Diet program'),
        ),
    ]
