# Generated by Django 4.2 on 2023-10-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_freedailydietprogram_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freedietprogram',
            options={'ordering': ('id',), 'verbose_name': 'برنامه غذایی رایگان', 'verbose_name_plural': 'برنامه های غذایی رایگان'},
        ),
    ]
